package dev.darcro.http2;

public enum HpackErrorReason {
    DECODER_FAILED,
    ENCODED_BLOCK_TOO_LARGE,
    HEADER_LIST_TOO_LARGE,
    TRUNCATED_INPUT,
    INTEGER_OVERFLOW,
    INVALID_INDEX,
    INVALID_HUFFMAN,
    INVALID_TABLE_SIZE_UPDATE,
    INVALID_REPRESENTATION
}
